/** @type {import('stylelint').Config} */
export default {
  extends: ['stylelint-config-standard-scss'],
  plugins:
    ['stylelint-order'],
  rules: {
    'order/order': [
      'custom-properties',
      'declarations',
    ],
    'order/properties-order': [
      'position',
      'top',
      'bottom',
      'right',
      'left',
      'display',
      'align-items',
      'justify-content',
      'float',
      'clear',
      'overflow',
      'overflow-x',
      'overflow-y',
      'margin',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'padding',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'font-size',
      'font-family',
      'font-weight',
      'text-align',
      'text-justify',
      'text-indent',
      'text-overflow',
      'text-decoration',
      'white-space',
      'color',
      'background',
      'background-position',
      'background-repeat',
      'background-size',
      'background-color',
      'background-clip',
      'border',
      'border-style',
      'border-width',
      'border-color',
      'border-top-style',
      'border-top-width',
      'border-top-color',
      'border-right-style',
      'border-right-width',
      'border-right-color',
      'border-bottom-style',
      'border-bottom-width',
      'border-bottom-color',
      'border-left-style',
      'border-left-width',
      'border-left-color',
      'border-radius',
      'opacity',
      'filter',
      'list-style',
      'outline',
      'visibility',
      'z-index',
      'box-shadow',
      'text-shadow',
      'resize',
      'transition',
    ],

    // === Stylelint Config Generator 產出的設定規則 ===

    // 'indentation': 2,
    // 'string-quotes': 'single',
    // 'no-duplicate-selectors': true,
    // 'selector-combinator-space-after': 'always',
    // 'declaration-colon-space-after': 'always',
    // 'number-leading-zero': 'never',
    // 'rule-empty-line-before': 'always-multi-line',
    // 'selector-pseudo-element-colon-notation': 'double',
    // 'media-feature-range-operator-space-before': 'always',
    // 'media-feature-range-operator-space-after': 'always',
    // 'media-feature-colon-space-after': 'always',
  },
  fix: true,

}
